import { Faction } from '@/components/general-card';
import { TacticType, TacticRank, Characteristic } from '@/components/tactic-card';

export const generalsData = [
    {
        name: '姜維',
        faction: '蜀' as Faction,
        rarity: 5,
        image: '/images/jiang_wei.png',
        tags: ['槍', 'S5'],
        attributes: {
            strength: '101(2.39)',
            intelligence: '111(2.65)',
            command: '91(2.11)',
            initiative: '76(1.15)',
        },
        tactic: {
            name: '九伐中原',
            image: '/images/jiu_fa_zhong_yuan.png',
            lv1: '每个回合结束时進行1-3次討伐：對敵軍隨機兩人造成20%-22.2%兵刃和謀略傷害。我軍全體造成傷害後會使當前回合討伐傷害係數提升2.5%~2.7%，可提升9次。累積討伐3次後使敵軍兵力最低單體產生逃兵（受智力和武力影響)',
            lv10: '每个回合結束時進行1-3次討伐：對敵軍隨機兩人造成20%-40%兵刃和謀略傷害。我軍全體造成傷害後會使當前回合討伐傷害係數提升2.5%~5%，可提升9次。累積討伐3次後使敵軍兵力最低單體產生逃兵（受智力和武力影響）',
        },
        affinity: {
            title: '薪火相傳',
            member: 'sp諸葛亮、劉備、姜維',
            effect: '部隊中緣分武將智力和統帥提升6%',
        },
    },
    {
        name: '曹操',
        faction: '魏' as Faction,
        rarity: 5,
        image: '/images/jiang_wei.png',
        tags: ['輔助', '防禦'],
        attributes: { strength: "72(1.95)", intelligence: "91(2.31)", command: "99(2.70)", initiative: "58(1.02)" },
        tactic: {
            name: '亂世奸雄',
            image: '/images/jiu_fa_zhong_yuan.png',
            lv1: '戰鬥中，使我軍群體造成的傷害提高8%，受到的傷害降低4%。',
            lv10: '戰鬥中，使我軍群體造成的傷害提高16%（受智力影響），受到的傷害降低10%（受智力影響）。若自身為副將，則每回合恢復兵力。',
        },
        affinity: {
            title: '魏武強軍',
            member: '曹操、曹仁、夏侯惇、夏侯淵',
            effect: '使我軍全體統帥提升20點。',
        },
    },
    {
        name: '孫權',
        faction: '吳' as Faction,
        rarity: 5,
        image: '/images/jiang_wei.png',
        tags: ['爆發', '光環'],
        attributes: { strength: "67(1.85)", intelligence: "80(2.15)", command: "89(2.21)", initiative: "65(1.18)" },
        tactic: {
            name: '坐斷東南',
            image: '/images/jiu_fa_zhong_yuan.png',
            lv1: '自身發動普通攻擊後，有35%概率隨機獲得連擊、洞察、先攻、必中、破陣狀態中的一種。',
            lv10: '自身發動普通攻擊後，有75%概率隨機獲得連擊、洞察、先攻、必中、破陣狀態中的一種，持續2回合。自身為主將時，優先獲得未擁有的狀態。',
        },
        affinity: {
            title: '三足鼎立',
            member: '曹操、劉備、孫權',
            effect: '戰鬥前2回合，使我軍全體造成的傷害提高10%。',
        },
    },
    {
        name: '呂布',
        faction: '群' as Faction,
        rarity: 5,
        image: '/images/jiang_wei.png',
        tags: ['武力', '單挑'],
        attributes: { strength: "100(3.04)", intelligence: "26(0.51)", command: "92(2.15)", initiative: "74(1.41)" },
        tactic: {
            name: '天下無雙',
            image: '/images/jiu_fa_zhong_yuan.png',
            lv1: '對敵軍單體發起決鬥，決鬥雙方輪流向對方發動普通攻擊，持續3回合。自身有概率獲得先攻。',
            lv10: '對敵軍單體發起決鬥，決鬥雙方輪流向對方發動普通攻擊，持續3回合。期間自身獲得先攻狀態且不受挑釁影響，普通攻擊觸發追擊戰法的概率提高7%。',
        },
        affinity: {
            title: '飛將奇緣',
            member: '呂布、貂蟬、高順、陳宮',
            effect: '使自身武力提升25點。',
        },
    },
];

export const tacticsData = [
    {
        name: '奇正相生',
        type: '指揮' as TacticType,
        rank: '橙' as TacticRank,
        characteristic: '治療' as Characteristic,
        rate: '100%',
        lv1: '第2回合起，回合開始時，有65%概率恢復我軍隨機兩人兵力(治療率為75%，受智力影響），回合結束時，有65%概率對敵軍隨機兩人造成75%謀略傷害',
        lv10: '第2回合起，回合開始時，有65%概率恢復我軍隨機兩人兵力(治療率為75%-150%，受智力影響），回合結束時，有65%概率對敵軍隨機兩人造成75%-150%謀略傷害',
        image: '/images/jiu_fa_zhong_yuan.png',
    },
    {
        name: '威震華夏',
        type: '主動' as TacticType,
        rank: '橙' as TacticRank,
        characteristic: '兵刃' as Characteristic,
        rate: '40%',
        lv1: '對敵軍全體發動一次猛烈進攻（傷害率70%），並有概率使其進入技窮或繳械狀態。',
        lv10: '對敵軍全體發動一次猛烈進攻（傷害率140%），並有概率使其進入技窮或繳械狀態，持續1回合。',
        source: '關羽',
        image: '/images/jiu_fa_zhong_yuan.png',
    },
    {
        name: '太平要術',
        type: '指揮' as TacticType,
        rank: '橙' as TacticRank,
        characteristic: '謀略' as Characteristic,
        rate: '100%',
        lv1: '提升自身謀略傷害6%，並在每回合開始時為友軍恢復兵力。',
        lv10: '提升自身謀略傷害12%（受智力影響），並在每回合開始時為友軍恢復兵力（治療率80%）。',
        source: '法正',
        image: '/images/jiu_fa_zhong_yuan.png',
    },
    {
        name: '橫掃千軍',
        type: '主動' as TacticType,
        rank: '橙' as TacticRank,
        characteristic: '兵刃' as Characteristic,
        rate: '45%',
        lv1: '對敵軍全體造成物理傷害（傷害率50%），若目標已處於控制狀態，則有概率使其震懾。',
        lv10: '對敵軍全體造成物理傷害（傷害率100%），若目標已處於控制狀態，則有30%概率使其進入震懾狀態，持續1回合。',
        source: '趙雲',
        image: '/images/jiu_fa_zhong_yuan.png',
    },
    {
        name: '破陣摧堅',
        type: '主動' as TacticType,
        rank: '橙' as TacticRank,
        characteristic: '文武' as Characteristic,
        rate: '35%',
        lv1: '準備一回合，使敵軍群體降低統率與智力40點，並造成一次物理傷害。',
        lv10: '準備一回合，使敵軍群體降低統率與智力80點（受武力影響），並造成一次物理傷害（傷害率158%）。',
        source: '孫策',
        image: '/images/jiu_fa_zhong_yuan.png',
    },
    {
        name: '刮骨療毒',
        type: '主動' as TacticType,
        rank: '橙' as TacticRank,
        characteristic: '治療' as Characteristic,
        rate: '40%',
        lv1: '為我軍損兵最多的單體清除負面狀態並恢復兵力（治療率128%）。',
        lv10: '為我軍損兵最多的單體清除負面狀態並恢復兵力（治療率256%，受智力影響）。',
        source: '華佗',
        image: '/images/jiu_fa_zhong_yuan.png',
    },
    {
        name: '盛氣凌敵',
        type: '指揮' as TacticType,
        rank: '橙' as TacticRank,
        characteristic: '防禦' as Characteristic,
        rate: '100%',
        lv1: '戰鬥前兩回合，使敵軍群體有45%概率進入繳械狀態。',
        lv10: '戰鬥前兩回合，使敵軍群體有90%概率進入繳械狀態，每回合獨立判定。',
        source: '顏良',
        image: '/images/jiu_fa_zhong_yuan.png',
    },
    {
        name: '草船借箭',
        type: '主動' as TacticType,
        rank: '紫' as TacticRank,
        characteristic: '輔助' as Characteristic,
        rate: '45%',
        lv1: '移除我軍群體的負面狀態，並使受到的傷害按比例轉化為恢復。',
        lv10: '移除我軍群體的負面狀態，並使受到的傷害按20%比例轉化為恢復，持續2回合。',
        source: '諸葛瑾',
        image: '/images/jiu_fa_zhong_yuan.png',
    },
];
